env:
  browser: true
  es6: true
  webextensions: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended

globals:
  ClassicEditor: false
  Jose: false
  JoseJWE: false
  Kinto: false
  KintoClient: false
  TestPilotGA: false
  checkIndexedDbHealth: false
  customizeEditor: false
  formatFooterTime: false
  fxaCryptoRelier: false
  fxaFetchProfile: false
  fxaRenewCredential: false
  getPadStats: false
  localizeEditorButtons: false
  migrationCheck: false
  migrationNote: false
  migrationBody: false
  retrieveNote: false
  setAnimation: false
  BrowserStorageCredentials: false
  loadFromKinto: false
  disconnectFromKinto: false
  saveToKinto: false
  createNote: false
  deleteNote: false

plugins:
  - jsx-a11y
  - react

settings:
  react:
    version: "16.2"

root: true

rules:
  no-lonely-if: warn
  consistent-return: warn
  eqeqeq: error
  linebreak-style: [error, unix]
  no-console: warn
  no-var: error
  prefer-const: error
  quotes: [error, single]
  semi: [error, always]
